# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20170202_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
