# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20170202_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
